# Generated by Django 3.2.15 on 2022-10-01 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', multiselectfield.db.fields.MultiSelectField(choices=[('lessons_1', 'Piano'), ('lessons_2', 'Theory')], max_length=19)),
                ('lesson_type', multiselectfield.db.fields.MultiSelectField(choices=[('lesson_type1', 'Online'), ('lesson_type2', 'Offline')], max_length=25)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
