# Generated by Django 3.2.15 on 2022-10-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20221006_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'ordering': ['-date'], 'verbose_name': 'Bookings', 'verbose_name_plural': 'Bookings'},
        ),
    ]
