# Generated by Django 3.2.15 on 2022-10-06 21:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20221006_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingstatus',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('status1', 'Upcoming'), ('status2', 'Completed')], max_length=15),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('lessons_1', 'Piano'), ('lessons_2', 'Theory')], max_length=19),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='lesson_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('lesson_type1', 'Online'), ('lesson_type2', 'Offline')], max_length=25),
        ),
    ]
