# Generated by Django 3.2.15 on 2022-10-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20221007_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingstatus',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='lesson_type',
            field=models.CharField(max_length=20),
        ),
    ]
