# Generated by Django 3.2.15 on 2022-10-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_bookingstatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingstatus',
            name='name',
        ),
        migrations.AlterField(
            model_name='bookingstatus',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
