# Generated by Django 3.2.15 on 2022-10-09 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20221009_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='past',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='past1', to='booking.bookingstatus'),
        ),
        migrations.AddField(
            model_name='bookingstatus',
            name='past',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status1', to='booking.bookingstatus'),
        ),
    ]
