# Generated by Django 3.2.15 on 2022-10-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20221009_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingstatus',
            name='past',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
