# Generated by Django 3.2.15 on 2022-10-10 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_alter_bookingstatus_past'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='past',
        ),
        migrations.RemoveField(
            model_name='bookingstatus',
            name='past',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingstatus'),
        ),
    ]
