# Generated by Django 3.2.15 on 2022-10-14 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_auto_20221014_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='lesson_type',
        ),
    ]
