# Generated by Django 3.2.15 on 2022-10-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_auto_20221014_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='bookings',
            unique_together=set(),
        ),
    ]
