# Generated by Django 3.2.15 on 2022-10-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0024_alter_bookings_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='lesson',
            field=models.CharField(default='pi', max_length=50),
        ),
        migrations.AddField(
            model_name='bookings',
            name='lesson_type',
            field=models.CharField(default='pi', max_length=50),
        ),
    ]
