# Generated by Django 3.2.15 on 2022-10-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_auto_20221014_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='lesson',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='lesson_type',
            field=models.CharField(max_length=50),
        ),
    ]
