# Generated by Django 3.2.15 on 2022-10-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_auto_20221014_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
