# Generated by Django 3.2.15 on 2022-10-14 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_bookings_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingStatus',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='LessonType',
        ),
    ]
